router:
  build: ./router
  ports:
    - "8080:80"
  volumes:
    - "./router/nginx.conf:/etc/nginx/nginx.conf:ro"
  #links:
    #- api
#web:
  #build: ./web
  #links:
    #- api
#api:
  #build: ./api
