router:
  build: ./router
  ports:
    - "8080:80"
  volumes:
    - "./router/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "./router/dnsmasq.conf:/etc/dnsmasq.conf:ro"
  links:
    - web
web:
  build: ./web
  #links:
    #- api
#api:
  #build: ./api
