router:
  build: ./router
  ports:
    - "8080:80"
  volumes:
    - "./router/nginx.conf.erb:/tmp/nginx.conf.erb:ro"
    - "./router/dnsmasq.conf:/etc/dnsmasq.conf:ro"
  links:
    - web
  dns_search:
    - "empire"
web:
  build: ./web
  links:
    - api
api:
  build: ./api
